server:
  port: 10086 # 服务端口
spring:
  application:
    name: eurekaserver # eureka的服务名称
eureka:
  client:
    registerWithEureka: false  #是否自己注册自己
    fetchRegistry: false  #是否从server拉取注册信息
    service-url:  # eureka的地址信息
      defaultZone: http://localhost:10086/eureka


